### ISSUE TITLE
Screen flickers when stacking popups

### ISSUE THREAD

**Issue by klaytonkowalski** [britzl/monarch#89] opened 2023-01-24 16:09 UTC
A = Not a popup
B = Popup
C = Popup

Screen stack = [ A, B ]

According to [Popup on popup](https://github.com/britzl/monarch#popup-on-popup), pushing C to the screen stack should replace B and the stack would look like: [A, C]. Unfortunately B doesn't wait until C is ready to be shown, so A is flickered before C is shown.

A while back, Monarch had a black screen flicker problem that had its own branch. That problem was fixed, but it was more focused on switching non-popup screens I think. It would be great if this could be fixed for popups.

**Comment by britzl** [comment] 2023-02-08 15:53
I'm looking into this now. I'm able to reproduce the flicker.

**Comment by britzl** [comment] 2023-02-09 22:57
> I'm able to reproduce the flicker.

It is not really a flicker. In this scenario when you have one popup shown and you show another popup the behaviour depends on if you have configured the popup to allow another popup to be shown on top of it (ie "Popup on Popup" checked) or if the first popup should be closed before the next one is shown.

In your case "Popup on Popup" is not checked and this means that the currently visible popup is closed. Monarch will wait until the popup has been hidden before loading and showing the new popup.

The flicker you are referring to is the frame after the first popup has been hidden and the new one is shown. Remember that this probably is perceived as flicker since you have no transitions on the two popups. With a transition it becomes more obvious that the first popup is closed and a new one is shown.

If you don't want this you could check Popup on Popup in which case the first popup is not closed.

**Comment by britzl** [comment] 2023-02-16 22:33
@klaytonkowalski does this make sense? I'll close the ticket and you can reopen it if you still think there is a problem that need to be addressed in Monarch.

**Closed by britzl** 2023-02-16 22:33 UTC
