### ISSUE TITLE
Unload then load collection - show both screens for a moment

### ISSUE THREAD

**Issue by AGulev** [britzl/monarch#15] opened 2018-05-10 08:41 UTC
For example we have 2 collections: 
first with 8 drawcalls
second with 9 drawcalls
In our project settings we set limit to 16 drawcalls.
When I try to unload one of the collection and load other using monarch, it looks like I have one or some frames when both collection rendered and I recieve an error:
WARNING:RENDER: Renderer is out of resources, some objects will not be rendered.

**Comment by britzl** [comment] 2018-05-25 05:58
I took a look at the code and came to the conclusion that this is by design. When you show a new screen a long sequence of things happen:

* The previous screen will start to unload in a coroutine (like this: https://github.com/britzl/monarch/blob/master/monarch/monarch.lua#L227-L243)
* The unload is asynchronous. The unload will involve things like removing input, sending focus lost message, playing a transition and then finally unloading the collection
* While all this is happening the new screen will be loaded in another coroutine (like this: https://github.com/britzl/monarch/blob/master/monarch/monarch.lua#L249-L269)
* The load is also asynchronous and it involves many things, more or less in the opposite order of an unload: load the collection, playing the transition, sending a focus gained message and lastly acquiring input

This means, as you can see from the sequence above and by reading the code that the two collections will be loaded at the same time while the old screen is transitioning out and the new one in. This is needed in case you want transitions such as one screen sliding out and the next one sliding in immediately adjacent to the one sliding out.

We could potentially add an option to hide the old screen first and then show the next one once the old one is hidden.

**Comment by AGulev** [comment] 2018-05-25 06:30
Yeah, I agree with you. I read the code but forgot to close this issue.
It's not important thing for now.
Thank you.

**Comment by britzl** [comment] 2018-05-25 09:13
Ok, good. Closing for now. If you need to be able to wait for unload before loading the next screen then please open a new ticket.

**Closed by britzl** 2018-05-25 09:13 UTC
Labels: investigation
