### ISSUE TITLE
show(nostack=true) + hide = bad behaviour

### ISSUE THREAD

**Issue by Morgerion** [britzl/monarch#78] opened 2021-07-14 13:50 UTC
Here is a screenshot of the situation:
![image_2021-07-14_16-23-09](https://user-images.githubusercontent.com/7888071/125633386-063962a4-7bf8-4c4f-80e3-52c5c2a6d698.png)

There is a window **hint_info**.
It opens with **show(nostack=true)**.
It closes with **hide()**.

Details of the problem:
1. hint_info window has a checkbox to keep the focus for the parent window. But when hint_info is opened, parent window loses focus permanently.
2. hint_info window has a popup type, but the parent window is still removed from the stack and there is no return to it after hide().

On version 3.3.0 there were no such problems - this code worked correctly.

**Comment by britzl** [comment] 2021-07-19 22:31
> It opens with show(nostack=true).
> 1. hint_info window has a checkbox to keep the focus for the parent window

Hmm, but if it is not added to the stack it shouldn't have a parent window at all. Why is it shown with nostack=true if you want it to interact with windows in the stack?

**Comment by britzl** [comment] 2021-08-02 20:38
@Morgerion any update?

**Comment by Morgerion** [comment] 2021-08-02 20:55
I apologise, perhaps I didn't describe the problem well.

So.
Yes, we have a window with no-stack.
Problem №1: when we open it, the parent window loses its input/focus, even though the no-stack window has checkbox "others keep input focus when below...".
Problem №2: closing a window with a non-stack removes the parent window from the stack! O_O

This seems to me to be a strange behavior for a no-stack window.
As a reminder, everything worked fine before.

We solved this problem simply by getting rid of the no-stack window.

**Comment by britzl** [comment] 2021-08-19 12:52
Sorry for the late reply. Thank you for clarifying the problem.

* Issue no.2 is definitely a bug. A screen that is shown with `no_stack` should never in any way manipulate the stack.
* Issue no.1. is a bit tricker. The no_stack option was mainly created as a way to load and hide screens without interaction, such as a background image or similar. I'm actually not able to reproduce the problem. Can you tell me a bit more about the two screens? Were they both normal screens or was one or both of them popups?

**Comment by Morgerion** [comment] 2021-08-19 13:28
One window (parent) is a normal full-screen in-stack window.
The second window (popup) is an no-stack popup.

Unfortunately I can't reproduce this problem now either, because we solved it a long time ago by doing away with no-stack windows. You can try to reproduce the same settings I have shown in the screenshot above.

**Comment by britzl** [comment] 2021-08-19 13:35
Thanks. I'll see if I can repro the problem. But I think it is better to be careful with no_stack windows and use them mainly for static things such as backgrounds

**Comment by britzl** [comment] 2021-09-19 20:48
> Thanks. I'll see if I can repro the problem

I'm unable to reproduce the problem. Closing this issue for now.

**Closed by britzl** 2021-09-19 20:48 UTC
Labels: more info
